"""Added messages

Revision ID: 037dede3a8c4
Revises: 54111aef3719
Create Date: 2024-09-11 09:03:55.149163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037dede3a8c4'
down_revision = '54111aef3719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
